on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "docker login"
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: "buildin image"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/BD .

      - name: "push image"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/BD
