on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: سحب الكود
        uses: actions/checkout@v3

      - name: تسجيل الدخول لـ Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.token }}

      - name: بناء صورة الـ Docker
        run: docker build -t ${{ secrets.username }}/bd .

      - name: رفع صورة الـ Docker
        run: docker push ${{ secrets.username }}/bd